# Choose the file format to load data from
format: "xls"
# Data location
data_dir: "/media/windowsC/SIN_Desktop/ENCHANT/ECHOES/data"
# Output directory kept out of git repo to save space
out_dir: "../../echoes/plots"
# Handle each survey. Like conditional parsing, plot histogram summaries of the data etc
surveys:
    'global':
        'histogram':
            'enable': true
            'ROWS': 10
            'COLS': 10
            'SIZE': [8*8, 6*8]
            'padding': 1.0
        'conditioning': 'substitute_nan'
    'survey_energy_provider':
        'histogram':
            'enable': true
    'int_survey':
        'histogram':
            'ROWS': 23
            'COLS': 19
            'SIZE': [8*10, 6*10]
    'psych_experiment_Spain':
        'histogram':
            'ROWS': 5
            'COLS': 11
    'psych_experiments_Germany_1':
        'histogram':
            'ROWS': 11
            'COLS': 11
    'psych_experiments_Germany_2':
        'histogram':
            'ROWS': 11
            'COLS': 12
    'psych_experiments_Bulgaria':
        'histogram':
            'ROWS': 10
            'COLS': 10
    'psych_experiments_Finland':
        'histogram':
            'ROWS': 8
            'COLS': 10
    'psych_experiments_Italy':
        'histogram':
            'ROWS': 13
            'COLS': 13
    'psych_experiments_Norway':
        'histogram':
            'ROWS': 8
            'COLS': 10
    'psych_experiments_Turkey':
        'histogram':
            'ROWS': 11
            'COLS': 10
            
